# Generated by Django 4.2.13 on 2024-05-23 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_keys', '0002_accesskey_name'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('access_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='access_keys.accesskey')),
            ],
        ),
        migrations.DeleteModel(
            name='AccessKey',
        ),
    ]
