# Generated by Django 5.0.6 on 2024-05-28 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_submission_created_at_submission_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Submission",
        ),
    ]
