# Generated by Django 5.0.6 on 2024-06-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_spam",
            field=models.BooleanField(default=False),
        ),
    ]
