# Generated by Django 4.2.13 on 2024-05-28 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesskey",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accesskey",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="accesskey",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
