# Generated by Django 4.2.13 on 2024-05-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='name',
            field=models.CharField(default='', max_length=125),
            preserve_default=False,
        ),
    ]
