# Generated by Django 5.0.6 on 2024-05-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0002_accesskey_created_at_accesskey_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesskey",
            name="plan",
            field=models.CharField(
                choices=[("free", "Free"), ("plus", "Plus"), ("elite", "Elite")],
                default="free",
                max_length=10,
            ),
        ),
    ]
