# Generated by Django 5.0.6 on 2024-06-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0003_accesskey_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
