# Generated by Django 5.0.6 on 2024-06-01 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0003_accesskey_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("plus", "Plus"),
                            ("elite", "Elite"),
                        ],
                        default="free",
                        max_length=10,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True, max_length=125, null=True, unique=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="accesskey",
            name="email",
        ),
        migrations.RemoveField(
            model_name="accesskey",
            name="plan",
        ),
        migrations.AddField(
            model_name="accesskey",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keys",
                to="access_keys.simpleuser",
            ),
            preserve_default=False,
        ),
    ]
