# Generated by Django 5.0.6 on 2024-06-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0004_simpleuser_alter_accesskey_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpleuser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
