# Generated by Django 5.0.6 on 2024-06-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0004_simpleuser_remove_accesskey_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpleuser",
            name="auto_reply",
            field=models.BooleanField(default=False),
        ),
    ]
