# Generated by Django 5.0.6 on 2024-06-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0006_remove_simpleuser_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpleuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="simpleuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="simpleuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
