# Generated by Django 5.0.6 on 2024-06-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0007_simpleuser_is_active_simpleuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpleuser",
            name="has_verified_email",
            field=models.BooleanField(default=False),
        ),
    ]
