# Generated by Django 5.0.6 on 2024-06-08 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0008_simpleuser_has_verified_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_responder_enabled", models.BooleanField(default=False)),
                (
                    "auto_responder_from_name",
                    models.CharField(default="Your Company Name", max_length=125),
                ),
                (
                    "auto_responder_subject",
                    models.CharField(
                        default="Auto Responder Email Subject", max_length=125
                    ),
                ),
                (
                    "autro_responder_intro_text",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("auto_responder_include_copy", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
