# Generated by Django 5.0.6 on 2024-06-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0009_usersettings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersettings",
            old_name="autro_responder_intro_text",
            new_name="auto_responder_intro_text",
        ),
    ]
