# Generated by Django 5.0.6 on 2024-06-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "access_keys",
            "0010_rename_autro_responder_intro_text_usersettin"
            "gs_auto_responder_intro_text",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="notion_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
