# Generated by Django 5.0.6 on 2024-06-08 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0011_usersettings_notion_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("database", models.CharField(max_length=125)),
                (
                    "access_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="access_keys.accesskey",
                    ),
                ),
            ],
        ),
    ]
