# Generated by Django 5.0.6 on 2024-06-08 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0012_notionlink"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notionlink",
            old_name="database",
            new_name="database_id",
        ),
        migrations.AddField(
            model_name="notionlink",
            name="database_name",
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notionlink",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notion_links",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
