# Generated by Django 5.0.6 on 2024-06-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0013_rename_database_notionlink_database_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notionlink",
            unique_together={("database_id", "access_key")},
        ),
    ]
