# Generated by Django 5.0.6 on 2024-06-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0016_alter_notionlink_access_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpleuser",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, default="", max_length=125, unique=True),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="auto_responder_intro_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="notion_token",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
