# Generated by Django 5.0.6 on 2024-06-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0017_alter_simpleuser_stripe_subscription_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpleuser",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, default="", max_length=125),
        ),
    ]
