# Generated by Django 5.0.6 on 2024-06-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0018_alter_simpleuser_stripe_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesskey",
            name="name",
            field=models.CharField(default="Access Key", max_length=125),
        ),
    ]
