# Generated by Django 5.0.6 on 2024-06-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_keys", "0019_alter_accesskey_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="whitelisted_domains",
            field=models.TextField(blank=True, default=""),
        ),
    ]
